class AlreadyExistsError(Exception):
    pass


class NotExistsError(Exception):
    pass
